version: "3.7"

services:
  breedbase:

    image: breedbase/breedbase:v1.09  

    container_name: breedbase_citrus_web
    ports:
      - 8103:8080
    volumes:
      - type: bind
        source: /export/prod/public_citrus
        target: /home/production/volume
      - type: bind
        source: empty_db_without.test_users.sql
        target: /home/production/empty_dump.sql
      - type: bind
        source: sgn_local.conf
        target: /home/production/cxgn/sgn/sgn_local.conf
      - type: bind
        source: /home/production/citrus/mason
        target: /home/production/cxgn/citrus/mason
      - type: bind
        source: /home/production/citrus/footer_body.mas
        target: /home/production/cxgn/sgn/mason/site/footer/body.mas
      - type: bind
        source: /home/production/citrus/analytics.mas
        target: /home/production/cxgn/citrus/mason/site/header/analytics.mas
      - type: bind
        source: db_dumps
        target: /db_dumps
      - type: bind
        source: crontab
        target: /etc/crontab
      - type: bind
        source: bash_history
        target: /root/.bash_history

volumes:
  webdata:




